[project]
name = "semantic-scholar"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "flask>=3.1.1",
    "flask-cors>=4.0.0",
    "requests>=2.32.4"
]
